#!/usr/bin/env python3
"""Generate sentences-data.js from all exercise HTML files."""
import re, json, os

os.chdir(os.path.join(os.path.dirname(__file__), '..'))

def extract_sentences(filename):
    with open(filename, encoding='utf-8') as f:
        text = f.read()
    m = re.search(r'const sentences = (\[[\s\S]*?\n\];)', text)
    if not m:
        print(f'NOT FOUND in {filename}')
        return None
    arr_text = m.group(1).rstrip(';')
    # Remove JS single-line comments
    arr_text = re.sub(r'//[^\n]*', '', arr_text)
    # Remove blank lines
    arr_text = re.sub(r'\n\s*\n', '\n', arr_text)
    # Quote all unquoted JS object keys: word: -> "word":
    arr_text = re.sub(r'(?<!["\w])([a-zA-Z_]\w*)\s*:', r'"\1":', arr_text)
    # Remove trailing commas before ] or }
    arr_text = re.sub(r',\s*([\]\}])', r'\1', arr_text)
    try:
        return json.loads(arr_text)
    except Exception as e:
        print(f'JSON error in {filename}: {e}')
        # Show context around error
        err_str = str(e)
        char_match = re.search(r'char (\d+)', err_str)
        if char_match:
            pos = int(char_match.group(1))
            print('Context:', repr(arr_text[max(0, pos-40):pos+40]))
        return None

files = [
    ('gerund-only.html',       'gerundOnly'),
    ('infinitive-only.html',   'infinitiveOnly'),
    ('bare-infinitive.html',   'bareInfinitive'),
    ('both-forms.html',        'bothForms'),
]

result = {}
for filename, key in files:
    data = extract_sentences(filename)
    if data is not None:
        result[key] = data
        print(f'{filename} -> {key}: {len(data)} sentences OK')

with open('sentences-data.js', 'w', encoding='utf-8') as f:
    f.write('// Auto-generated by scripts/gen_sentences_data.py\n')
    f.write('// Do not edit manually — run the script to regenerate\n')
    f.write('window.sentencesData = ')
    f.write(json.dumps(result, ensure_ascii=False, separators=(',', ':')))
    f.write(';\n')

total = sum(len(v) for v in result.values())
print(f'\nsentences-data.js written: {total} total sentences across {len(result)} keys')
