#!/usr/bin/env python3
"""Generate sentences-data.js from all 4 conditional HTML files."""
import re, json, os

os.chdir(os.path.join(os.path.dirname(__file__), '..'))

result = {}
for n, key in [('0','cond0'),('1','cond1'),('2','cond2'),('3','cond3')]:
    with open(f'{n}.html', encoding='utf-8') as f:
        text = f.read()
    m = re.search(r'const sentences = (\[[\s\S]*?\n\];)', text)
    if not m:
        print(f'NOT FOUND in {n}.html'); continue
    arr_text = m.group(1).rstrip(';')
    # Remove JS single-line comments (// ...)
    arr_text = re.sub(r'//[^\n]*', '', arr_text)
    # Remove blank lines
    arr_text = re.sub(r'\n\s*\n', '\n', arr_text)
    # Quote unquoted JS object keys: {words: -> {"words":  and  ,ru: -> ,"ru":
    arr_text = arr_text.replace('{words:', '{"words":').replace(',ru:', ',"ru":')
    try:
        data = json.loads(arr_text)
        result[key] = data
        print(f'{n}.html -> {key}: {len(data)} sentences OK')
    except Exception as e:
        # Show context around error
        err_str = str(e)
        char_match = re.search(r'char (\d+)', err_str)
        if char_match:
            pos = int(char_match.group(1))
            print(f'JSON error in {n}.html: {e}')
            print('Context:', repr(arr_text[max(0,pos-40):pos+40]))
        else:
            print(f'JSON error in {n}.html: {e}')

with open('sentences-data.js', 'w', encoding='utf-8') as f:
    f.write('// Auto-generated by scripts/gen_sentences_data.py\n')
    f.write('// Do not edit manually — run the script to regenerate\n')
    f.write('window.sentencesData = ')
    f.write(json.dumps(result, ensure_ascii=False, separators=(',',':')))
    f.write(';\n')

total = sum(len(v) for v in result.values())
print(f'\nsentences-data.js written: {total} total sentences across {len(result)} keys')
