#!/usr/bin/env node
/**
 * release.js — автоматический релиз
 *
 * Использование:
 *   node scripts/release.js patch   → 1.1.0 → 1.1.1
 *   node scripts/release.js minor   → 1.1.0 → 1.2.0
 *   node scripts/release.js major   → 1.1.0 → 2.0.0
 *   node scripts/release.js 2.3.0   → конкретная версия
 *
 * Что делает:
 *   1. Читает/обновляет версию в package.json
 *   2. Генерирует version.js
 *   3. Создаёт releases/v{version}/notes.md (если не существует)
 *   4. git add -A  →  git commit  →  git tag  →  git push
 */

const fs   = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const ROOT = path.resolve(__dirname, '..');

// ── 1. Определяем новую версию ────────────────────────────────────────────────
const pkgPath = path.join(ROOT, 'package.json');
const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));

const arg = process.argv[2];
if (!arg) {
  console.error('Usage: node scripts/release.js patch|minor|major|<version>');
  process.exit(1);
}

let [major, minor, patch] = pkg.version.split('.').map(Number);
if (arg === 'patch')       { patch += 1; }
else if (arg === 'minor')  { minor += 1; patch = 0; }
else if (arg === 'major')  { major += 1; minor = 0; patch = 0; }
else if (/^\d+\.\d+\.\d+$/.test(arg)) {
  [major, minor, patch] = arg.split('.').map(Number);
} else {
  console.error(`Unknown argument: ${arg}`);
  process.exit(1);
}

const newVersion = `${major}.${minor}.${patch}`;
const vTag = `v${newVersion}`;

// ── 2. Обновляем package.json ─────────────────────────────────────────────────
pkg.version = newVersion;
fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n');
console.log(`package.json → version: ${newVersion}`);

// ── 3. Генерируем version.js ──────────────────────────────────────────────────
const versionJs = `// AUTO-GENERATED by scripts/release.js — do not edit manually.
// Single source of truth for the displayed app version.
(function () {
  var VERSION = '${vTag}';
  var el = document.createElement('div');
  el.id = 'app-version';
  el.textContent = VERSION;
  el.style.cssText =
    'position:fixed;bottom:10px;right:14px;' +
    'font-size:11px;color:#2e2e46;' +
    'font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;' +
    'user-select:none;pointer-events:none;z-index:9999;';
  document.body.appendChild(el);
})();
`;
fs.writeFileSync(path.join(ROOT, 'version.js'), versionJs);
console.log(`version.js   → ${vTag}`);

// ── 4. Создаём папку релиза с заметками ──────────────────────────────────────
const releaseDir = path.join(ROOT, 'releases', vTag);
const notesPath  = path.join(releaseDir, 'notes.md');
if (!fs.existsSync(releaseDir)) {
  fs.mkdirSync(releaseDir, { recursive: true });
}
if (!fs.existsSync(notesPath)) {
  fs.writeFileSync(notesPath,
`# ${vTag} — ${new Date().toISOString().slice(0, 10)}

## Что нового
-

## Исправления
-

## Технические изменения
-
`);
  console.log(`releases/${vTag}/notes.md → создан (заполни перед пушем)`);
} else {
  console.log(`releases/${vTag}/notes.md → уже существует`);
}

// ── 5. Git: add → commit → tag → push ────────────────────────────────────────
const run = (cmd) => execSync(cmd, { cwd: ROOT, stdio: 'inherit' });

run('git add -A');
run(`git commit -m "Release ${vTag}"`);
run(`git tag ${vTag}`);
run('git push origin main --tags');

console.log(`\n✓ ${vTag} задеплоен!`);
